### ISSUE TITLE
Removing an element while dragging

### ISSUE THREAD

**Issue by SteGlaset** [emp74ark/pma#79]
https://user-images.githubusercontent.com/90640042/204111439-d849a522-f259-4028-b491-7553a474e6c6.mov

What i mean:

https://user-images.githubusercontent.com/90640042/204111396-f6799ab1-d78f-4db4-9193-72671e9af535.mov

**Comment by emp74ark** [comment]
Do you want to implement ability to remove item by drag it to free space of board?

**Comment by emp74ark** [comment]
Done
